# Generated by Django 5.0.2 on 2024-05-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec', models.CharField(max_length=200)),
                ('rate', models.FloatField(default=0.0)),
            ],
        ),
    ]
